Update ptxdist to 2024.12.0

diff --git a/projectroot/etc/rc.once.d/dropbear b/projectroot/etc/rc.once.d/dropbear
--- a/projectroot/etc/rc.once.d/dropbear
+++ b/projectroot/etc/rc.once.d/dropbear
@@ -2,32 +2,44 @@
 
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 
-DROPBEAR_RSAKEY_DEFAULT="@KEYDIR@/dropbear_rsa_host_key"
-DROPBEAR_DSSKEY_DEFAULT="@KEYDIR@/dropbear_dss_host_key"
-
-test -n "$DROPBEAR_RSAKEY" || \
-  DROPBEAR_RSAKEY=$DROPBEAR_RSAKEY_DEFAULT
-test -n "$DROPBEAR_DSSKEY" || \
-  DROPBEAR_DSSKEY=$DROPBEAR_DSSKEY_DEFAULT
+. /usr/lib/init/dropbear.sh
 
 gen_key() {
-
 	key_type=$1
 	key_file=$2
 
+	# do not overwrite valid key files
+	[ -s "$key_file" ] && dropbearkey -y -f "$key_file" > /dev/null 2>&1 && return
+
 	rm -f $key_file > /dev/null 2>&1
 
-	echo -n "generating $key_type key..."
-	dropbearkey -t $key_type -f $key_file > /dev/null 2>&1
-
-	if [ "$?" = "0" ]; then
-		echo "done"
-	else
-		echo "failed"
-		exit 1
-	fi
+	echo "Create $key_type key; this may take some time ..."
+	dropbearkey -t $key_type -f $key_file > /dev/null 2>&1 || return
+	echo "Created $key_type key."
 }
 
-[ -e "$DROPBEAR_RSAKEY" ] || gen_key rsa "$DROPBEAR_RSAKEY"
-[ -e "$DROPBEAR_DSSKEY" ] || gen_key dss "$DROPBEAR_DSSKEY"
+gen_keys() {
+	for keytype in $DROPBEAR_KEYTYPES
+	do
+		case "$keytype" in
+			rsa)
+				gen_key rsa "$DROPBEAR_RSAKEY" || return
+				;;
+			ecdsa)
+				gen_key ecdsa "$DROPBEAR_ECDSAKEY" || return
+				;;
+			ed25519)
+				gen_key ed25519 "$DROPBEAR_ED25519KEY" || return
+				;;
+			*)
+				echo "Key type '$keytype' not supported"
+				;;
+		esac
+	done
+}
 
+if ! gen_keys
+then
+	echo "Generating SSH keys failed!"
+	exit 1
+fi
diff --git a/scripts/git-ptx-patches b/scripts/git-ptx-patches
--- a/scripts/git-ptx-patches
+++ b/scripts/git-ptx-patches
@@ -6,7 +6,7 @@
 # behaviour or patch output.
 pristine_git() {
 	# Notes from the git(1) manpage:
-	# - GIT_DIFF_OPTS takes takes precedence over -U command line parameter
+	# - GIT_DIFF_OPTS takes precedence over -U command line parameter
 	HOME=/nonexistent \
 	XDG_CONFIG_HOME=/nonexistent \
 	GIT_CONFIG_NOSYSTEM=true \
@@ -33,7 +33,9 @@ if [ ! -L .ptxdist/series ]; then
 fi
 
 remove_old=no
-tag=base
+tag=
+numbered_patches=true
+all_tags=false
 
 if grep -q "$PTX_PATCHES_HEADER" .ptxdist/series; then
 	echo "Found series file generated by git-ptx-patches."
@@ -52,21 +54,80 @@ if [ "x$1" = "x--force-remove" ]; then
 	shift
 fi
 
-while getopts "ft:n:" opt; do
+while getopts "aft:n" opt; do
 	case "${opt}" in
+		a)
+			all_tags=true
+			;;
 		f)
 			remove_old="force"
 			;;
 		t)
 			tag="${OPTARG}"
-			range="${tag}"
+			;;
+		n)
+			numbered_patches=false
 			;;
 	esac
 done
 shift $((${OPTIND} - 1))
 
-tag2=$(grep "#tag:" .ptxdist/series | awk "/#tag:${tag}/{if (getline) print \$1}" | sed 's,#tag:,,')
+
+tags=( $(sed -n 's/^#tag:\([^ ]*\) .*/\1/p' .ptxdist/series 2>/dev/null) )
+
+# default to the first tag if none was specified,
+# use 'base' if there is no tag at all
+if [ -z "${tag}" ]; then
+	tag="${tags[0]}"
+fi
+if [ -z "${tag}" ]; then
+	tag="base"
+fi
+
+# only look for the second tag if there are tags in the series
+# otherwise assume all commits should be exported
+if [ ${#tags[*]} -gt 0 ]; then
+	tag2=$(awk -F "[ :]" "
+/^#tag:/ {
+	if (state == 1) {
+		print \$2
+		state=2
+	}
+}
+/^#tag:${tag}( |\$)/ {
+	state=1
+}
+END {
+	if (!state)
+		exit 1
+}" < .ptxdist/series)
+
+	if [ $? -ne 0 ]; then
+		echo "Failed to find tag '${tag}' in the series"
+		exit 1
+	fi
+else
+	tags=( "${tag}" )
+	tag2=""
+fi
+
 range="${tag}..${tag2}"
+
+if "${all_tags}" ; then
+	args=()
+	if [ "${remove_old}" = "force" ]; then
+		args[${#args[*]}]="-f"
+	fi
+	if ! "${numbered_patches}"; then
+		args[${#args[*]}]="-n"
+	fi
+	for tag in "${tags[@]}"; do
+		echo "Updating patches for '${tag}'..."
+		"$0" "${args[@]}" -t "${tag}" || break
+		echo
+	done
+	exit
+fi
 
 echo "$PTX_PATCHES_HEADER" > .ptxdist/series.0
 :> .ptxdist/series.1
@@ -143,14 +204,28 @@ fi
 
 GIT_EXTRA_ARGS="$GIT_EXTRA_ARGS --summary --stat=80"
 
-cat .ptxdist/series.0 > .ptxdist/series
-${GIT} format-patch -N $GIT_EXTRA_ARGS ${tagopt} -o .ptxdist/patches/ ${range} | sed -e 's,^.ptxdist/patches/,,' > .ptxdist/series.auto
-cat .ptxdist/series.auto >> .ptxdist/series
-cat .ptxdist/series.1 >> .ptxdist/series
+${GIT} format-patch -N $GIT_EXTRA_ARGS ${tagopt} -o .ptxdist/patches/ ${range} | while read patch; do
+	if "$numbered_patches"; then
+		patchname="${patch#.ptxdist/patches/}"
+	else
+		patchname="${patch#.ptxdist/patches/[0-9][0-9][0-9][0-9]-}"
+		mv -n "$patch" ".ptxdist/patches/$patchname"
+	fi
+	echo "$patchname"
+done > .ptxdist/series.auto
+
+cat .ptxdist/series.0 .ptxdist/series.auto .ptxdist/series.1 > .ptxdist/series
 cat .ptxdist/series | _md5sum >> .ptxdist/series
 
 # The first line of the patch is 'From <some-git-hash> ...'
 # remove it to avoid unnecessary changes in the patch files.
+while read patch para; do
+	# There are no comments or empty lines in series.auto, so no need to
+	# handle these. Also be a bit cautious to only remove lines matching
+	# "^From ".
+	sed -i '1{/^From /d}' ".ptxdist/patches/$patch"
+done < .ptxdist/series.auto
+
 find .ptxdist/patches/ ! -type d | sed -e 's,^.ptxdist/patches/,,' | \
 while read patch para; do
 	case "$patch" in
@@ -158,14 +233,11 @@ while read patch para; do
 		*) ;;
 	esac
 	if grep -q "$patch" .ptxdist/series.auto; then
-		p=".ptxdist/patches/$patch"
-		tail -n+2 "$p" > ".$patch.ptx-patches"
-		mv ".$patch.ptx-patches" "$p"
+		# ok, this is one of the patches we just touched
+		:
+	elif grep -q "$patch" .ptxdist/series.{0,1}; then
+		echo "Base patch \"$patch\"!"
 	else
-		if grep -q "$patch" .ptxdist/series.{0,1}; then
-			echo "Base patch \"$patch\"!"
-		else
-			echo "Old patch \"$patch\"!"
-		fi
+		echo "Old patch \"$patch\"!"
 	fi
 done | sort
diff --git a/scripts/pkg-config-wrapper b/scripts/pkg-config-wrapper
--- a/scripts/pkg-config-wrapper
+++ b/scripts/pkg-config-wrapper
@@ -1,25 +1,30 @@
 #!/usr/bin/env bash
-
-basedir="$(basename "$(dirname "$(dirname "$0")")")"
+sysroot="$(dirname "$(dirname "$(dirname "$0")")")"
+basedir="$(basename "${sysroot}")"
 
 declare -a prefix
 if [ "${basedir}" = "sysroot-cross" ]; then
-    sysroot="$(dirname "$(dirname "$(dirname "$0")")")/sysroot-target"
+    sysroot="$(dirname "${sysroot}")/sysroot-target"
     prefix="${sysroot}/usr"
     whitelist="${PKGCONFIG_WHITELIST_TARGET}"
 elif [ "${basedir}" = "sysroot-host" ]; then
-    sysroot="$(dirname "$(dirname "$0")")"
-    prefix="${sysroot}"
+    prefix="${sysroot}/usr"
     whitelist="${PKGCONFIG_WHITELIST_HOST}"
 else
     echo "$(basename ${0}): failed to determine prefix" >&2
     exit 1
 fi
 
-declare -a libdir system_path system_incpath
-libdir=( "${prefix/%//lib/pkgconfig}" "${prefix/%//share/pkgconfig}" )
-system_libpath=( "${libdir[@]/%//../../lib}" "${libdir[@]/%//../lib}" "/usr/lib" "/lib" )
-system_incpath=( "${libdir[@]/%//../../include}" "${libdir[@]/%//../include}" "/usr/include" "/include" )
+declare -a libdirs libpaths incpaths
+# try to find all our pkgconfig paths.
+libdirs=( $(find ${prefix} -maxdepth 3 -type d -name pkgconfig) )
+for libdir in "${libdirs[@]}"; do
+    lib="$(basename $(dirname ${libdir}))"
+    libpaths+=( "${libdir[@]/%//../../${lib}}" "${libdir[@]/%//../${lib}}" )
+    incpaths+=( "${libdir[@]/%//../../include}" "${libdir[@]/%//../include}" )
+    libpaths+=( "/usr/${lib}" "/${lib}" )
+done
+incpaths+=( "/usr/include" "/include" )
 
 orig_IFS="${IFS}"
 IFS=":"
@@ -30,12 +35,12 @@ unset PKG_CONFIG_SYSROOT_DIR
 # they may include /usr/{lib,include} which is never correct
 unset PKG_CONFIG_ALLOW_SYSTEM_CFLAGS
 unset PKG_CONFIG_ALLOW_SYSTEM_LIBS
-# default pkg-config searchs
-export PKG_CONFIG_LIBDIR="${libdir[*]}"
+# default pkg-config search path
+export PKG_CONFIG_LIBDIR="${libdirs[*]}"
 # default search path that will be dropped from --libs
-export PKG_CONFIG_SYSTEM_LIBRARY_PATH="${system_libpath[*]}"
+export PKG_CONFIG_SYSTEM_LIBRARY_PATH="${libpaths[*]}"
 # default search path that will be dropped from --cflags
-export PKG_CONFIG_SYSTEM_INCLUDE_PATH="${system_incpath[*]}"
+export PKG_CONFIG_SYSTEM_INCLUDE_PATH="${incpaths[*]}"
 IFS="${orig_IFS}"
 
 for ((i = 1; i <= ${#}; i++)); do
@@ -78,14 +83,48 @@ check_pipe_status() {
 	done
 }
 
-if [ -n "${PKGCONFIG_WHITELIST_SRC}" ]; then
-    pkgs="$(pkg-config.real --print-provides "${@}" 2>/dev/null | awk '{print $1}' && check_pipe_status)" &&
+print_pkg() {
+    args=()
+    while [ $# -gt 0 ]; do
+	case "${1}" in
+	    --variable|--define-variable|--atleast-pkgconfig-version|--*-version)
+		shift
+		;;
+	    --*)
+		;;
+	    *)
+		args[${#args[@]}]="${1}"
+		;;
+	esac
+	shift
+    done
+    if [ ${#args[*]} -ne 0 ]; then
+	pkgconf --print-provides "${args[@]}" 2> "${error}" | awk '{print $1}' &&
+	check_pipe_status
+    fi
+}
+
+if [ -n "${PKGCONFIG_WHITELIST_SRC}" -a "${1}" != "--version" -a "${1}" != "--help" ]; then
+    error="$(mktemp "${PTXDIST_TEMPDIR}/pkg-config.XXXXXX")"
+    pkgs="$(print_pkg "${@}")"
+    if [ $? -ne 0 ]; then
+	# meson suppresses any pkg-config output, so dump it into the logfile instead
+	if [ "${pkg_conf_tool}" = "meson" -a -n "${PTXDIST_LOGFILE_PATH}" ]; then
+	    echo "$(basename ${0}) $*" >>"${PTXDIST_LOGFILE_PATH}"
+	    cat "${error}" >>"${PTXDIST_LOGFILE_PATH}"
+	else
+	    cat "${error}" >&2
+	fi
+	rm "${error}"
+	exit 1
+    fi
+    rm "${error}"
     for pkg in ${pkgs}; do
 	if [[ ! " ${whitelist} " =~ " ${pkg} " && ! "${pkg}" =~ '-uninstalled' ]]; then
-	    echo "$(basename ${0}): warning: blocking '${pkg}': not selected by '${PKGCONFIG_WHITELIST_SRC}'" >&2
+	    echo "$(basename ${0}): warning: blocking '${pkg}': not selected by '${PKGCONFIG_WHITELIST_SRC}'" >&${ERROR_FD}
 	    exit 1
 	fi
     done
 fi
-pkg-config.real "${@}" | sed "${args[@]}"
+pkgconf "${@}" | sed "${args[@]}"
 check_pipe_status
